### ISSUE TITLE
Progress document

### ISSUE THREAD

**Issue by DavidMichaelRoberts** [agrothendieck/agrothendieck.github.io#1]
Is it possible to have a plain text document that lists each chapter/major section (ie. contents table, references, etc) and notes whether it is a) in progress b) text complete, but diagrams in progress c) typed, but needs to be checked or d) typed and checked ? Or similar.

**Comment by carmonamateo** [comment]
In fact, I had in mind something related, take a look https://agrothendieck.github.io/lab.html I'm still working on it...

**Comment by DavidMichaelRoberts** [comment]
Oh, that's excellent! Even better. I was only thinking for this particular document, but progress is so fast it's not really worth tracking, I guess.
