### ISSUE TITLE
Notations

### ISSUE THREAD

**Issue by DavidMichaelRoberts** [agrothendieck/agrothendieck.github.io#2]
1. Can we use the cmtip option for xypic, so that the arrowheads in the text and the diagrams are the same?
1. When we have references to displayed maths that has a `(*)` or `(**)`, we should pick a style that matches across the actual label and the reference, so both text or both maths.

**Comment by DavidMichaelRoberts** [comment]
Or better, \xyoption{tips}, following [the documentation](http://texdoc.net/texmf-dist/doc/generic/xypic/xyrefer.pdf) (I just learned that cmtip was an old approach, only still works for backwards compatibility)

**Comment by carmonamateo** [comment]
> 1. Can we use the cmtip option for xypic, so that the arrowheads in the text and the diagrams are the same? Or better, \xyoption{tips}.

I suppose I agree, but I do not know how to proceed. May you please do that?


> 2. When we have references to displayed maths that has a (*) or (**), we should pick a style that matches across the actual label and the reference, so both text or both maths.

I think it is advisable if we leave the transcription as faithful as possible, but we can use this recommendation in the project of translation.

**Comment by DavidMichaelRoberts** [comment]
1. OK I will do it. It's a global document option, will be relatively easy
1. What I mean is we should probably either have both `$(*)$` style (in text and as equation labels) or both `\text{(*)}`. As it stands some are one and some are the other. The maths mode `$*$` and the text mode `*` look quite different.

**Comment by DavidMichaelRoberts** [comment]
So for example compare Proposition 3.3.6 vs Definition 4.4.1

**Comment by carmonamateo** [comment]
Oh! I see, of course, it is better, I indeed prefer \text{(*)}...

**Comment by DavidMichaelRoberts** [comment]
OK, I'll go through and change them. I'd changed the arrowheads, the Euler font style looks better than the Computer Modern ones, though the match is not perfect.
