### ISSUE TITLE
audio files for lectures?

### ISSUE THREAD

**Issue by natdwight** [agrothendieck/agrothendieck.github.io#5]
Do you know where the audio files (mp3) are for Grothendieck's Buffalo lectures? I can't seem to download the files from the Audio section.

Many thanks

**Comment by kipiberbatov** [comment]
You can find all the links in the [index.thml](https://github.com/agrothendieck/agrothendieck.github.io/blob/2e3c9b9244be9a880e2bbfd82fa420e9bb93db79/index.html) page (note that this is a stable link to a particular commit).
Just search (Ctrl + F) for the files containing the string **audio/wav** or **audio/mp3**.
The **WAV** files can be listened (in French) directly in the browser at https://cds.cern.ch/record/912518/ or you can download them from the links on lines 1719, 1724, 1729.
The rest are the **MP3** files (source lines 1751--2515).
For instance, on line 1754 you can find the code for the first **MP3** file:
```
<source src="http://docs.google.com/uc?export=open&id=1sbOy5FgRem-iK1xsh4cCdJAbF5iBa7e7" type="audio/mp3">
```
So, you just open the file **http://docs.google.com/uc?export=open&id=1sbOy5FgRem-iK1xsh4cCdJAbF5iBa7e7**.
Proceed in the same way for the rest of the files.

**Comment by carmonamateo** [comment]
Apologies for the delay! You can find all the audios and much more here: https://csg.igrothendieck.org/
